# Generated by Django 4.1 on 2022-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.CharField(max_length=4294967295)),
                ('shortUrl', models.CharField(max_length=4294967295)),
            ],
        ),
    ]
