# Generated by Django 4.1 on 2022-08-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLS'},
        ),
        migrations.AddField(
            model_name='urls',
            name='urlCode',
            field=models.CharField(default=None, max_length=4294967295),
        ),
    ]
