# Generated by Django 4.1 on 2022-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_urls_options_urls_urlcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='multipleCode',
            field=models.CharField(default='[]', max_length=4294967295),
        ),
    ]
