# Generated by Django 4.1 on 2022-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_urls_multiplecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='multipleCode',
            field=models.TextField(default='[]', max_length=4294967295),
        ),
    ]
